export const theme = {
  ltr: "ltr",
  rtl: "rtl",
  paragraph: "font-sans dark:text-dark-text",
  quote: "editor-quote",
  heading: {
    h1: "text-6xl font-bold",
    h2: "text-4xl font-bold",
    h3: "text-2xl font-bold",
    h4: "editor-heading-h4",
    h5: "editor-heading-h5",
    h6: "editor-heading-h6",
  },
  list: {
    nested: {
      listitem: "list-inside",
    },
    ol: "list-decimal ml-8",
    ul: "list-disc ml-8",
    listitem: "mb-2",
    listitemChecked: "editor-listItemChecked",
    listitemUnchecked: "editor-listItemUnchecked",
  },
  hashtag: "editor-hashtag",
  image: "editor-image",
  link: "text-blue-500 underline cursor-pointer",
  text: {
    bold: "font-bold",
    code: "editor-textCode",
    italic: "italic",
    strikethrough: "line-through",
    subscript: "editor-textSubscript",
    superscript: "editor-textSuperscript",
    underline: "underline",
    underlineStrikethrough: "editor-textUnderlineStrikethrough",
  },
  code: "bg-gray-100 dark:bg-black font-mono block p-2 pl-14 leading-6 text-xs m-0 mt-2 mb-2 tab-[2] ",
  codeHighlight: {
    atrule: "text-purple-600 font-bold",
    attr: "text-pink-500",
    boolean: "text-blue-500 font-bold",
    builtin: "text-indigo-500",
    cdata: "text-gray-400 italic",
    char: "text-green-600",
    class: "text-orange-500",
    "class-name": "text-yellow-500 font-semibold",
    comment: "text-gray-500 italic",
    constant: "text-blue-600",
    deleted: "text-red-600 line-through",
    doctype: "text-gray-400 italic",
    entity: "text-cyan-500",
    function: "text-blue-500",
    important: "text-red-500 font-bold",
    inserted: "text-green-500",
    keyword: "text-purple-700 font-bold",
    namespace: "text-gray-600",
    number: "text-blue-400",
    operator: "text-red-400",
    prolog: "text-gray-500 italic",
    property: "text-teal-500",
    punctuation: "text-gray-700",
    regex: "text-green-500",
    selector: "text-indigo-500",
    string: "text-green-600",
    symbol: "text-pink-500",
    tag: "text-red-500 font-semibold",
    url: "text-blue-400 underline",
    variable: "text-orange-600",
  },
};
